api:
  port: 10300
authentication:
  config: ""
  enable: false
  jwtConfig:
    filePath: ""
    key: ""
    signatureType: ""
  type: ""
authorization:
  autoReload: 0
  enable: false
  filePath: ""
  policyData: ""
  url: ""
broker:
  diskSyncSeconds: 60
  maxConn: 0
  maxPayload: 104857600
  parallelRecovery: 2
  readBufferSize: 2
  sliceMaxAgeSeconds: 0
  sliceMaxBytes: 64
  sliceMaxMessages: 0
  writeBufferSize: 2
  writeDeadline: 2000
client:
  apiAddress: http://localhost:10300
  authToken: ""
  clientId: ""
  grpcHost: localhost
  grpcPort: 50000
grpc:
  bodyLimit: 104857600
  port: 50000
  subBuffSize: 100
log:
  level: info
queue:
  defaultVisibilitySeconds: 60
  defaultWaitTimeoutSeconds: 1
  maxDelaySeconds: 43200
  maxExpirationSeconds: 43200
  maxInflight: 2048
  maxNumberOfMessages: 1024
  maxReceiveCount: 1024
  maxVisibilitySeconds: 43200
  maxWaitTimeoutSeconds: 3600
  pubAckWaitSeconds: 60
rest:
  bodyLimit: ""
  cors:
    allowCredentials: false
    allowHeaders: []
    allowMethods:
    - GET
    - POST
    allowOrigins:
    - '*'
    exposeHeaders: []
    maxAge: 0
  port: 9090
  readTimeout: 60
  subBuffSize: 100
  writeTimeout: 60
routing:
  autoReload: 0
  data: ""
  enable: false
  filePath: ""
  url: ""
security:
  ca:
    data: ""
    filename: ""
  cert:
    data: ""
    filename: ""
  key:
    data: ""
    filename: ""
store:
  cleanStore: false
  maxMessages: 0
  maxPurgeInactive: 1440
  maxQueueSize: 0
  maxQueues: 0
  maxRetention: 1440
  maxSubscribers: 0
  storePath: ./store
